### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by Lily-WL** [matsen/pplacer#349]
Dear Sir,

I am a new to use pplacer and confronted some problems during the installation. Can you help to figure it out? The main problems are two actions failed ( ocaml-gsl 0.6.3 and sqlite3 1.6.3) during installing required OCaml packages. The feedback information was as follows。 Thank you very much for your time! Best!

[root@student pplacer-1.1.alpha17]# cat opam-requirements.txt | xargs opam install -y
[WARNING] Running as root is not recommended
The following actions will be performed:
.......
===== ∗ 19 =====

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] https://opam.ocaml.org/archives/camlzip.1.05+opam.tar.gz downloaded
......

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗ installed camlp4.4.01
∗ installed ocamlbuild.0
∗ installed conf-m4.1
∗ installed conf-pkg-config.1.0
∗ installed conf-ncurses.1
∗ installed ocamlfind.1.6.2
[ERROR] The compilation of ocaml-gsl failed at "make".
∗ installed camlzip.1.05
∗ installed ocamlify.0.0.1
∗ installed ocamlmod.0.0.8
[ERROR] The compilation of sqlite3 failed at "./configure --prefix
/root/.opam/3.12.1".
∗ installed ounit.1.1.2
∗ installed type_conv.108.08.00
∗ installed xmlm.1.1.1
∗ installed ocaml-data-notation.0.0.11
∗ installed mcl.12-068oasis4
∗ installed batteries.2.1.0
∗ installed oasis.0.3.0
∗ installed csv.1.2.2

#=== ERROR while installing ocaml-gsl.0.6.3 ===================================#
opam-version 1.2.2
os linux
command make
path /root/.opam/3.12.1/build/ocaml-gsl.0.6.3
compiler 3.12.1
exit-code 2
env-file /root/.opam/3.12.1/build/ocaml-gsl.0.6.3/ocaml-gsl-17544-af57d6.env
stdout-file /root/.opam/3.12.1/build/ocaml-gsl.0.6.3/ocaml-gsl-17544-af57d6.out
stderr-file /root/.opam/3.12.1/build/ocaml-gsl.0.6.3/ocaml-gsl-17544-af57d6.err
........ stdout .........
ocamlc -ccopt ' -DHAVE_INLINE -DHAVE_FENV -g -O2 ' -c mlgsl_error.c
.........stderr..........
[...]
mlgsl_error.c:15: 错误：所在的函数内也只报告一次。)
mlgsl_error.c: 在函数‘ml_gsl_strerror’中:
mlgsl_error.c:22: 警告：隐式声明函数‘gsl_strerror’
mlgsl_error.c:22: 警告：传递‘caml_copy_string’的第 1 个参数时将整数赋给指针，未作类型转换
/root/.opam/3.12.1/lib/ocaml/caml/alloc.h:30: 附注：需要类型‘const char ’，但实参的类型为‘int’ mlgsl_error.c: 在函数‘ml_gsl_error_init’中:
mlgsl_error.c:56: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘attribute’ before ‘’ token
mlgsl_error.c:56: 错误：‘old’未声明(在此函数内第一次使用)
mlgsl_error.c:60: 警告：隐式声明函数‘gsl_set_error_handler’
make: *** [mlgsl_error.o] 错误 2

=== ERROR while installing sqlite3.1.6.3 =====================================
opam-version 1.2.2
os linux
command ./configure --prefix /root/.opam/3.12.1
path /root/.opam/3.12.1/build/sqlite3.1.6.3
compiler 3.12.1
exit-code 1
env-file /root/.opam/3.12.1/build/sqlite3.1.6.3/sqlite3-17544-876af6.env
stdout-file /root/.opam/3.12.1/build/sqlite3.1.6.3/sqlite3-17544-876af6.out
stderr-file /root/.opam/3.12.1/build/sqlite3.1.6.3/sqlite3-17544-876af6.err

stdout

[...]
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
configure: checking for C header files...
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
configure: checking libraries...
configure: checking for sqlite3 library...
checking for sqlite3_open in -lsqlite3... no
###stderr ###
configure: error: SQLite is required. See the --with-sqlite3 configure option.

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
∗ install ocaml-gsl 0.6.3
∗ install sqlite3 1.6.3
The following changes have been performed
∗ install batteries 2.1.0

∗ install camlp4 4.01

∗ install camlzip 1.05

∗ install conf-m4 1

∗ install conf-ncurses 1

∗ install conf-pkg-config 1.0

∗ install csv 1.2.2

∗ install mcl 12-068oasis4
∗ install oasis 0.3.0

∗ install ocaml-data-notation 0.0.11

∗ install ocamlbuild 0

∗ install ocamlfind 1.6.2

∗ install ocamlify 0.0.1

∗ install ocamlmod 0.0.8

∗ install ounit 1.1.2

∗ install type_conv 108.08.00

∗ install xmlm 1.1.1

=-=- sqlite3.1.6.3 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing.
`opam depext sqlite3.1.6.3' may help you find the correct installation for
your system.

The former state can be restored with:
opam switch import "~/.opam/3.12.1/backup/state-20160329080704.export"

**Comment by matsen** [comment]
Have you tried using the binaries we supply rather than compiling from scratch?

**Comment by Lily-WL** [comment]
Thank you for your reply.
When I installed the software, I downloaded the source code and installed it as the progress of wesite　（http://matsen.github.io/pplacer/compiling.html）.

Is it the matter with the operation system? I installed the soft ware on CentOS 6.3.

**Comment by Lily-WL** [comment]
OK. I can use "./pplacer" within the fold of the binaries. But How can I change the system path to let other software use it, such as "CheckM".

**Comment by matsen** [comment]
http://askubuntu.com/questions/440691/add-a-binary-to-my-path
