### ISSUE TITLE
Reference/query alignment question

### ISSUE THREAD

**Issue by nickswim9** [matsen/pplacer#353]
Hello,

I have two separate fasta files for query sequences and reference sequences, but they are not in the same frame and length. Do you have a recommendation as to what software to use to perform a multiple alignment to put them in the same frame and length? I was thinking of using something like muscle (http://www.ebi.ac.uk/Tools/msa/muscle/) but I wanted to check if there is a better one to use with pplacer.

Thanks,
Nick

**Comment by matsen** [comment]
This is covered here: http://matsen.github.io/pplacer/generated_rst/pplacer.html#making-alignments-for-use-with-pplacer

The commands may be a little out of date. Please suggest edits if that's the case.

http://biocore.github.io/pynast/ is also an option, but I have no experience with that.
