### ISSUE TITLE
Cannot run pplace with CheckM

### ISSUE THREAD

**Issue by itiago** [matsen/pplacer#355]
Have donwloaded pplacer-Linux-v1.1.alpha17.zip, unziped and runned : "python setup.py install"
then set path:

sudo nano /etc/bash.bashrc
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/pplacer
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/guppy
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/rppr

sudo nano /home/igor/.bashrc
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/pplacer
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/guppy
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/rppr

sudo nano /etc/profile

export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/pplacer
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/pplacer/scripts
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/guppy
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/rppr

THEN runned CheckM:

"igor@ubuntu:~/metaBAT/bin/AC3_ANVIo_metaBat_bining/CheckM_results$ checkm lineage_wf -x fa /home/igor/metaBAT/bin/AC3_ANVIo_metaBat_bining /home/igor/metaBAT/bin/AC3_ANVIo_metaBat_bining/CheckM_results/

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 45 bins with 1 threads:
    Finished processing 45 of 45 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 45 bins with 1 threads:
    Finished processing 45 of 45 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 45 of 45 (100.00%) bins.
  Extracting 43 HMMs with 1 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  [Error] Make sure pplacer is on your system path.

  Controlled exit resulting from an unrecoverable error or warning. "

Could you please help?
Thank you

**Comment by matsen** [comment]
This is a CheckM question.
