### ISSUE TITLE
unable to use pplacer in Windows environment

### ISSUE THREAD

**Issue by asmagaret** [matsen/pplacer#363]
Hi there Erick and compatriots,

I'm here at UW/FHCRC, trying to use pplacer on some microbiome data out of the Fredricks lab!  Excited, brand new package for me.  

After looking through your abundant documentation for a few hours, I can't seem to figure out if downloading the *.zip file "pplacer-1.1.alpha19.zip" should be enough to allow me to run pplacer at the Windows command line.  Curious if you can point to something in the documentation or can advise by some other means.  When I unzip both above named the zip file and the zip file for the tutorial, I try to run pplacer and I get this error message:
> pplacer pplacer_demo.sh
'pplacer' is not recognized as an internal or external command,...

Happy day to you.  -- Amalia

**Comment by matsen** [comment]
Sorry, Windows has never been supported.
