### ISSUE TITLE
Where can I find GPL-3 version of guppy and rppr

### ISSUE THREAD

**Issue by tillea** [matsen/pplacer#371]
Hi,
the README.ms says:

    pplacer, guppy, and rppr are free software under the GPL v3.

but I can not find any source for guppy and rppr.  My goal is to create official Debian packages from all three tools since these are relevant for the COVID-19 sprint of the Debian Med team.
Kind regards, Andreas.

**Comment by matsen** [comment]
They all get installed when you install the main pplacer package.

http://matsen.github.io/pplacer/compiling.html#building-pplacer
